### ISSUE TITLE
Host the builded game somewhere

### ISSUE THREAD

**Issue by rvetere** [phoboslab/q1k3#2]
Could you make a release here on github..? So that it would be possible to include the game in _any_ website just by adding a script tag pointing to the release here on github ;-) We would love to integrate it on our internal bootup-page of our frontend-project :D

**Comment by phoboslab** [comment]
I... don't really see the point of that, sorry. If you really want to do that, you can load the game from my website: https://phoboslab.org/q1k3/

Otherwise just fork this repo :)

**Comment by sibvrv** [comment]
**Github Pages**

Steps:
-  git checkout --orphan gh-pages
-  git rm -rf --dry-run .   _# preview files to be deleted_
-  git rm -rf .                    _# actually delete the files_

Now you can start adding files and commit them and they will live in their own branch.

Ex: https://sibvrv.github.io/Q1K3Mod/
