### ISSUE TITLE
Can I mirror this on my server?

### ISSUE THREAD

**Issue by wolffe** [phoboslab/q1k3#4]
This looks awesome! I played it 3 times already in the past 30 minutes.

Any way I can mirror it on [QuakeWiki.net](https://www.quakewiki.net/)? And am I allowed to do it?

**Comment by phoboslab** [comment]
Yes, you can do that. The code is under the MIT License, which allows even for commercial use. You just have to maintain the copyright notice.

I see you already have a page on the wiki for the game, with all the info. So you can just embed the code there if you want.

**Comment by wolffe** [comment]
I have just added an article about this - https://www.quakewiki.net/q1k3-a-javascript-homage-to-quake-in-just-13kb/ - with links to the project.

How would I go about mirrorring it? I have added the game page, but I am getting some console errors - https://www.quakewiki.net/q1k3/

**Comment by phoboslab** [comment]
You're missing the two data files:
- `l` with the compiled level data: https://phoboslab.org/q1k3/l
- `m` with the model data: https://phoboslab.org/q1k3/m

**Comment by wolffe** [comment]
Got it, I'll investigate.

Thanks!
